sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: pypy
    env: TOXENV=pypy
install:
- pip install tox
- pip install python-coveralls
- pip install codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sbuss
  password:
    secure: BGA4p5oEaBizDZe9q6bjItszJonBSJWxIe+uaAWZqHB+S0XDUV2oc9vIPTVn8AHiqW4fYxHaNzPrJ2+yd9GNRLh4vgQH24RJ3XaXG3z1RQp5HOb6lzS//h5IumU8nFTFZP2R5rNfBwi8ZK1SLtUk0FKhqB4CUFkoy1IRo55MQLg1QSqf5rK6KVflVKOyRbBCd2+mTyga4g2r1o2JEQ1/cnDt916B/io7KhgugliOPmh6oDWDYy5NOCQy9Jzg6mgAVeQJ7YyO5OpMOVyX49oGWgkmk2d1CWnOKie/gSHptIt9rrv4bBqDOIeqTC42Ti7MZNMcg7/lZJTYmdJL79Wgutc3vzOjwK4VrAq7gqO1h6aMWmi2o205ZLghvC7/4CISroUFblMN2KlzYL6rhiTeXTYMX2WwXtXESJBRBweKBfoMvwNuefWVUSPOAqwXJBzr8lbvoRkMu+HfGsYbXH/4FvEe1MPV76SI8gcd+Y1KAlclIdTbRG/zv3wutLDghIuUWu2XZ9SNV1hfeadZ5ys7iNqv4YQPV7vCGldoihcKheZKkswjUqdSDH7dHclXHi+U8zlXhfTAv4baqcIP5a2liWERRZKOv9s0ruZ/iGubCLFyc+2UXOXRPP1lBqjE8QZI1xVDlMDPBIvkS1ITSvSXVH9fTpbeIshO+azw/Nm7/lQ=
  on:
    tags: true
    repo: sbuss/py-multiaddr
    branch: master
    condition: "$TOXENV == py27"
